QandA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
	path('users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
	path('', views.index, name='index'),
	path('<int:post_id>/', views.detail, name='detail'),
	path('add_question/', views.add_question, name='add_question'),
	path('save_question/', views.save_question, name='save_question'),
	path('delete_question/', views.delete_question, name='delete_question'),
	path('<int:post_id>/save_answer/', views.save_answer, name='save_answer'),
	path('<int:post_id>/delete_answer/', views.delete_answer, name='delete_answer'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
	path('signup/', views.SignUp.as_view(), name='signup'),
	path('profile/<int:user_id>/', views.profile, name='profile'),
]

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.
class Question(models.Model):
	author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
	question_text = models.CharField(max_length=250)
	detail_text = models.CharField(max_length=1000)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return "Question: " + self.question_text + "\nDetail: " + self.detail_text

class Answer(models.Model):
	author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	answer_text = models.CharField(max_length=10000)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.answer_text

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class CustomUser(AbstractUser):

	def __str__(self):
		return self.username + ": " + self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

	class Meta(UserCreationForm):
		model = CustomUser
		fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

	class Meta:
		model = CustomUser
		fields = ('username', 'email')

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse

from .models import Question, Answer

# Create your views here. Start off with function-based views then switch to CBV
def index(request):
	question_list = Question.objects.order_by('-pub_date')
	context = {'question_list': question_list}
	return render(request, 'posts/index.html', context)

def detail(request, post_id):
	question = get_object_or_404(Question, pk=post_id)
	return render(request, 'posts/detail.html', {'question': question, 'answers': question.answer_set.all()})

def add_question(request):
	return render(request, 'posts/add_question.html', {})

def save_question(request):
	q = Question(question_text=request.POST['question'], detail_text=request.POST['detail'], 
			pub_date=timezone.now())
	q.save()

	if request.user.id:
		request.user.question_set.add(q)
		request.user.save()
		
	return HttpResponseRedirect(reverse('posts:detail', args=(q.id,)))

def delete_question(request):
	q = get_object_or_404(Question, pk=request.POST['question'])

	if request.user.id == q.author.id and request.user.id != None:
		q.delete()

	return HttpResponseRedirect(reverse('posts:index'))

def save_answer(request, post_id):
	q = get_object_or_404(Question, pk=post_id)
	answer = Answer(question=q, answer_text=request.POST['answer'], votes=0)

	if (request.user.id):
		answer.author = request.user

	answer.save()
	return HttpResponseRedirect(reverse('posts:detail', args=(post_id,)))

def delete_answer(request, post_id):
	answer = get_object_or_404(Answer, pk=request.POST['answer'])
	answer.delete()

	return HttpResponseRedirect(reverse('posts:detail', args=(post_id,)))

users/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.urls import reverse

from .forms import CustomUserCreationForm
from .models import CustomUser

# Create your views here.
class SignUp(generic.CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'signup.html'

def profile(request, user_id):
	user = get_object_or_404(CustomUser, pk=user_id)
	return render(request, 'users/profile.html', {
		'user': user, 
		'questions': user.question_set.all(), 
		'answers': user.answer_set.all()
	})

posts/templates/posts/add_question.html
{% extends 'base.html' %}

{% block title %}Add Question{% endblock %}

{% block content %}
<h1>Add a question</h1>

<form action="{% url 'posts:save_question' %}" method="post">
{% csrf_token %}
	Add Question: <input type="text" name="question">
	<br>
	Add Detail: <input type="text" name="detail">
	<br>
	<input type="submit" value="Submit">
</form>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
{% endblock %}

{% block title %}{{ question }}{% endblock %}

{% block content %}
<div class="question">
	<h1>{{ question.question_text }}</h1>
	<h2>{{ question.detail_text }}</h2>

	{% if question.author.id == request.user.id and request.user.id != None %}
	<form action="{% url 'posts:delete_question' %}" method="post">
	{% csrf_token %}
		<input type="hidden" name="question" value="{{ question.id }}">
		<input type="submit" value="Delete Question">
	</form>
	{% endif %}

	{% if question.author %}
		<p>Author: <a href="{% url 'users:profile' question.author.id %}">{{ question.author.username }}</a></p>
	{% else %}
		<p>Author: Anonymous</p>
	{% endif %}
</div>

<div class="answer">
	{% if answers %}
		<ol>
			{% for answer in answers %}
				{% if answer.author.username %}
					<li>
						{{ answer.answer_text }} | by <a href="{% url 'users:profile' answer.author.id %}">{{ answer.author.username }}</a>
						{% if request.user.id == answer.author.id and request.user.id != None %}
							<form action="{% url 'posts:delete_answer' question.id %}" method="post">
							{% csrf_token %}
								<input type="hidden" name="answer" value="{{ answer.id }}">
								<input type="submit" value="Delete Answer">
							</form>
						{% endif %}
					</li>
				{% else %}
					<li>{{ answer.answer_text }} | by Anonymous</li>
				{% endif %}
			{% endfor %}
		</ol>
	{% else %}
		<p>No answers are available</p>
	{% endif %}

	<form action="{% url 'posts:save_answer' question.id %}" method="post">
	{% csrf_token %}
		Add answer: <input type="text" name="answer">
		<input type="submit" value="Submit">
	</form>
</div>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}
{% if question_list %}
	<ol>
		{% for question in question_list %}
			<li><a href="{% url 'posts:detail' question.id %}">{{ question.question_text }}</a></li>
		{% endfor %}
	</ol>
{% else %}
	<p>No questions are available</p>
{% endif %}

<a href="{% url 'posts:add_question' %}">Add a question</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{% block title %}QandA{% endblock %}</title>

	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'QandA/base.css' %}">

	{% block head %}
	{% endblock %}
</head>
<body>
	<main>
		<header>
			{% if user.is_authenticated %}
				<p>Hi <a href="{% url 'users:profile' user.id %}">{{ user.username }}</a>!
				 | <a href="{% url 'logout' %}">logout</a></p>
			{% else %}
				<a href="{% url 'login' %}">login</a> | 
				<a href="{% url 'users:signup' %}"> signup</a> |
				<a href="{% url 'password_reset' %}"> reset password</a>
			{% endif %}
		</header>
		<h1 class="project-title"><a href="{% url 'posts:index' %}">QandA</a></h1>
		{% block content %}
		{% endblock %}
		<footer>
			<a href="{% url 'posts:index' %}">Return to index</a>
		</footer>
	</main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Sign up</button>
</form>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<h2>{{ user.username }}</h2>

<p><a href="{% url 'password_change' %}">change password</a></p>

<h3>Questions:</h3>
{% if questions %}
<ol>
	{% for question in questions %}
		<li><a href="{% url 'posts:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
</ol>
{% else %}
<p>You have not posted any questions.</p>
{% endif %}

<h3>Answers</h3>
{% if answers %}
<ol>
	{% for answer in answers %}
		<li><a href="{% url 'posts:detail' answer.question.id%}">{{ answer.answer_text }}</a></li>
	{% endfor %}
</ol>
{% else %}
<p>You have not posted any answers.</p>
{% endif %}

{% endblock %}